kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      // Non-Secure
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      // Secure
      - containerPort: 443
        hostPort: 443
        protocol: TCP
      // Database
      - containerPort: 30000
        hostPort: 5432
        protocol: TCP
