apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tense-mantis-ingress
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /api/v1
            backend:
              service:
                name: server
                port: 8080
