kind: PersistentVolume
apiVersion: v1
metadata:
  name: database-pv-volume
  labels:
    type: local
    app: database
spec:
  storageClassName: manual
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: database-pv-claim
  labels:
    app: database
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100M
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
  labels:
    app: database
data:
  POSTGRES_DB: database
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: test123
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: postgres:10.1
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: database-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: database
      volumes:
        - name: database
          persistentVolumeClaim:
            claimName: database-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app: database
spec:
  ports:
    - protocol: TCP
      port: 5432
  selector:
    app: database
---
apiVersion: v1
kind: Service
metadata:
  name: database-ext
  labels:
    app: database-ext
spec:
  type: NodePort
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 5432
      nodePort: 30000
